version: '3'

services:
  mongo:
    image: mongo
    container_name: ca-mongo
    restart: unless-stopped
    volumes:
      - ./db:/data/db
    logging:
      driver: none
  idxMongo:
    image: mongo
    container_name: ca-idx
    links:
      - mongo
    volumes:
      - ./config:/config
    command:
      - /config/run_idx.sh
    depends_on:
      - mongo
  bindaas:
    build: "./Deps/Bindaas/"
    image: sbubmi/quip_distro_bindaas:dev
    depends_on:
      - "mongo"
    container_name: ca-data
    restart: unless-stopped
    logging:
      driver: none
    ports: ["8080:8080", "9099:9099"]
    volumes:
      - ./config/bindaas_projects/:/root/bindaas/bin/projects/
      - ./config/bindaas.config.json:/root/bindaas/bin/bindaas.config.json
  iip:
    build: "https://github.com/camicroscope/iipImage.git#v3.2.0"
    image: sbubmi/quip_distro_iip:dev
    container_name: ca-iip
    restart: unless-stopped
    volumes:
      - ./images/:/data/images/
  security:
    build: "https://github.com/camicroscope/Security.git#v3.4.6"
    image: sbubmi/quip_distro_security:dev
    container_name: ca-security
    restart: unless-stopped
    ports: ["4010:4010"]
    volumes:
      - ./config/routes.json:/root/src/routes.json
    environment:
      - DISABLE_SEC=true
  auth:
    build: "./Deps/auth_service/"
    image: sbubmi/quip_distro_auth:dev
    container_name: ca-auth
    logging:
      driver: none
  pathdb:
    build: "https://github.com/SBU-BMI/PathDB.git#1.1.2"
    image: sbubmi/quip_distro_pathdb:dev
    container_name: quip-pathdb
    restart: unless-stopped
    ports: ["443:443","80:80"]
    volumes:
      - ./data:/data/
      - ./images/:/data/pathdb/files/wsi
      - ./config/pathdb:/quip/web/sites/default
      - ./jwt_keys/:/keys/
      - ./config:/config
    command:
      - /config/pathdb_pre.sh
  imageloader:
    build: "https://github.com/SBU-BMI/ImageLoader.git#1.1.0"
    image: sbubmi/quip_distro_imageloader:dev
    container_name: quip-imageloader
    volumes:
      - ./data:/data/
      - ./images:/data/images
    environment:
      - QUIP_IMAGE_PATH=$PWD/images
      - QUIP_DATA_PATH=$PWD/data
  segloader:
    build: "https://github.com/SBU-BMI/SegmentationLoader.git#1.0.1"
    image: sbubmi/quip_distro_segloader:dev
    container_name: quip-segloader
    volumes:
      - ./data:/data
  heatmaploader:
    build: "https://github.com/SBU-BMI/uploadHeatmaps.git#v1.5.0"
    image: sbubmi/quip_distro_heatmaploader:dev
    container_name: quip-hmloader
    ports: ["27017:27017"]
    volumes:
      - ./data:/mnt/data/
      
