apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f quip-pathdb.yml.PRISM -o openshift2
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: pathdb
  name: pathdb
spec:
  ports:
  - name: "443"
    port: 443
    targetPort: 8443
  - name: "80"
    port: 80
    targetPort: 8080
  selector:
    io.kompose.service: pathdb
status:
  loadBalancer: {}
