db.authorization.createIndex( { "name": 1 }, { unique: true } )
db.mark.createIndex({"geometries.features.bound":"2dsphere"})
db.mark.createIndex({"provenance": 1})
db.mark.createIndex({"provenance.image.slide": 1, "provenance.analysis.execution_id": 1})
db.mark.createIndex({"provenance.image.study": 1, "provenance.image.specimen": 1, "provenance.image.slide": 1})
db.slide.createIndex({'study':1, 'specimen': 1, 'name': 1})
db.template.createIndex({'id': 1})
db.template.createIndex({'name': 1})
db.heatmap.createIndex({"provenance.image.slide": 1, "provenance.analysis.execution_id": 1})
db.heatmap.createIndex({"provenance.image.study": 1, "provenance.image.specimen": 1, "provenance.image.slide": 1})
