name: Docker Compose Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the develop stack
        run: docker-compose -f develop.yml build
